Update dependencies and add custom LB protos
When the new Custom LB support is used by gRPC, this tool currently breaks with:

```
Error: proto: google.protobuf.Any: unable to resolve "type.googleapis.com/envoy.extensions.load_balancing_policies.wrr_locality.v3.WrrLocality": not found
```

Updating dependencies and adding these protos to main.go fixes this error.